# Generated by Django 5.2.17 on 2026-09-28 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='inventory/')),
                ('active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatedFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('incoming', 'Entrada prevista'), ('customer_commitment', 'Compromiso con cliente')], max_length=32)),
                ('client', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dated_flows', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dated_flows', to='operations.inventorybatch')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('available', models.DecimalField(decimal_places=3, max_digits=18)),
                ('observed_on', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.inventorybatch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('required_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('exported', 'Exportado'), ('superseded', 'Fuente sustituida')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('suggested_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('exported', 'Exportado')], default='pending', max_length=16)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_order_lines', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='operations.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('channel', models.CharField(default='telegram', max_length=32)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Error')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='operations.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='sales/')),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
                ('row_count', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='operations.salesdataset'),
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(blank=True, max_length=255)),
                ('distribution_channel', models.CharField(blank=True, max_length=255)),
                ('sales_channel', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.salesdataset')),
            ],
        ),
        migrations.CreateModel(
            name='StockCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('proposed_available', models.DecimalField(decimal_places=3, max_digits=18)),
                ('observed_on', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_stock_corrections', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_inventory_batch'),
        ),
        migrations.AddIndex(
            model_name='datedflow',
            index=models.Index(fields=['client', 'product', 'due_date', 'kind'], name='operations__client_c294f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='datedflow',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='dated_flow_quantity_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['batch', 'client', 'product'], name='operations__batch_i_53cb4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('batch', 'client', 'product'), name='inventory_pair_once'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('available__gte', 0)), name='inventory_available_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['status', 'order'], name='operations__status_1883fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='order_product_once'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gte', 0)), name='requested_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('approved_qty__isnull', True), ('approved_qty__gte', 0), _connector='OR'), name='approved_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_qty__isnull', True), ('suggested_qty__gte', 0), _connector='OR'), name='suggested_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesdataset',
            constraint=models.CheckConstraint(condition=models.Q(('last_date__gte', models.F('first_date'))), name='sales_dates_in_order'),
        ),
        migrations.AddConstraint(
            model_name='salesdataset',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_sales_dataset'),
        ),
        migrations.AddIndex(
            model_name='orderrequest',
            index=models.Index(fields=['client', 'required_date', 'status'], name='operations__client_8f8db6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesline',
            index=models.Index(fields=['dataset', 'date'], name='operations__dataset_0365de_idx'),
        ),
        migrations.AddIndex(
            model_name='salesline',
            index=models.Index(fields=['dataset', 'client', 'product', 'date'], name='operations__dataset_bd1854_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='sales_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salesline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='sales_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockcorrectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_available__gte', 0)), name='stock_correction_nonnegative'),
        ),
    ]
