# Generated by Django 5.2.17 on 2026-09-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='unit_match_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesdataset',
            name='full_snapshot_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
