# Generated by Django 5.2.17 on 2026-09-28 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_inventorybatch_unit_match_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='revalidated_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revalidated_orders', to='operations.salesdataset'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='revalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='revalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revalidated_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('available', models.DecimalField(decimal_places=3, max_digits=18)),
                ('observed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='operations.inventorybatch')),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='operations.stockcorrectionrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'client', 'product', '-created_at'], name='operations__batch_i_4c6374_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('available__gte', 0)), name='inventory_adjustment_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='OrderCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('day', models.DateField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='operations.orderline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'product', 'day'), name='one_order_per_product_day')],
            },
        ),
    ]
