# Generated by Django 5.2.17 on 2026-09-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_orderrequest_revalidated_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='inventory_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_at_creation', to='operations.inventorybatch'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='inventory_revalidated_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revalidated_orders', to='operations.inventorybatch'),
        ),
    ]
