# Generated by Django 5.2.17 on 2026-10-03 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_orderrequest_inventory_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderline',
            name='future_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='sale_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de producción'), ('approved', 'Producción autorizada'), ('rejected', 'Rechazado'), ('exported', 'Exportado')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de producción'), ('reviewed', 'Producción revisada'), ('exported', 'Exportado'), ('superseded', 'Fuente sustituida'), ('cancelled', 'Cancelado')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sale_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='sale_discount_range'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('future_quantity__isnull', True), ('future_quantity__gte', 0), _connector='OR'), name='future_quantity_nonnegative'),
        ),
        migrations.AddField(
            model_name='accessevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
