# Generated by Django 5.2.17 on 2026-10-03 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_sales_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooCustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OdooProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, unique=True)),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('unit', models.CharField(max_length=128)),
                ('source_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OdooOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('snapshot', models.JSONField(default=dict)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='odoo_link', to='operations.orderrequest')),
            ],
        ),
    ]
